### ISSUE TITLE
Exception about BaseAtomRef casting to Atom in matching symmetry

### ISSUE THREAD

**Issue by blurock** [blurock/JThermodynamics#9]
```
Exception in thread "main" java.lang.ClassCastException: org.openscience.cdk.AtomContainer2$BaseAtomRef cannot be cast to org.openscience.cdk.Atom
        at thermo.data.structure.structure.matching.IsolateConnectedStructure.IsolateConnectedStructure(IsolateConnectedStructure.java:50)
        at thermo.data.structure.structure.symmetry.utilities.DetermineSetOfSymmetryAssignments.findConnectedSubstructures(DetermineSetOfSymmetryAssignments.java:375)
        at thermo.data.structure.structure.symmetry.utilities.DetermineSetOfSymmetryAssignments.findSymmetryAssignments(DetermineSetOfSymmetryAssignments.java:194)
        at thermo.data.structure.structure.symmetry.utilities.DetermineSetOfSymmetryAssignments.findAllSetsOfSymmetryAssignments(DetermineSetOfSymmetryAssignments.java:117)
        at thermo.data.structure.structure.symmetry.utilities.DetermineSetOfSymmetryAssignments.findIfMatchInStructures(DetermineSetOfSymmetryAssignments.java:70)
        at thermo.data.structure.structure.symmetry.DetermineSymmetryFromSingleDefinition.determineSetOfSymmetryAssignments(DetermineSymmetryFromSingleDefinition.java:49)
        at thermo.data.structure.structure.symmetry.DetermineExternalSymmetryFromSingleDefinition.determineSymmetry(DetermineExternalSymmetryFromSingleDefinition.java:27)
        at thermo.data.structure.structure.symmetry.DetermineExternalSymmetry.determineSymmetry(DetermineExternalSymmetry.java:81)
        at thermo.data.structure.structure.symmetry.CalculateExternalSymmetryCorrection.calculate(CalculateExternalSymmetryCorrection.java:75)
        at thermo.data.structure.structure.symmetry.CalculateSymmetryCorrection.calculate(CalculateSymmetryCorrection.java:29)
        at thermo.compute.ComputeThermodynamicsFromMolecule.computeThermodynamicsForMolecule(ComputeThermodynamicsFromMolecule.java:328)
        at thermo.compute.ComputeThermodynamicsFromMolecule.computeThermodynamics(ComputeThermodynamicsFromMolecule.java:275)
        at thermo.compute.ComputeThermodynamicsFromMolecule.computeThermodynamics(ComputeThermodynamicsFromMolecule.java:199)
        at thermo.compute.ComputeThermodynamicsFromNancyString.computeFromNancyLinearForm(ComputeThermodynamicsFromNancyString.java:137)
        at thermo.compute.ComputeThermodynamicsFromNancyString.executeCommand(ComputeThermodynamicsFromNancyString.java:70)
        at thermo.LineCommands.main(LineCommands.java:18)


```

**Comment by blurock** [comment]
Fixed by casting to AtomRef in 
    public IAtomContainer IsolateConnectedStructure(IAtomContainer mol, IAtom connected, IAtom firstinstructure) {
...
        if(!noloop) {
        	AtomRef catm = new AtomRef(connected);
        	MetaRingAtom ringatm = new MetaRingAtom(catm);
        	substructure.addAtom(ringatm);
        }

However, there is a problem now with optical symmetry  (another issue)

```
BensonThermodynamicBase(c-(h)/2-(c)/2):	Reference: 'Benson20210129'
H298:  -5.00 S298:   9.65 [  300.0,  5.59] [  400.0,  7.08] [  500.0,  8.43] [  600.0,  9.53] [  800.0, 11.23] [ 1000.0, 12.48] [ 1500.0, 14.25]
BensonThermodynamicBase(c-(h)-(c)/3):	Reference: 'Benson20210129'
H298:  -2.14 S298: -11.43 [  300.0,  4.90] [  400.0,  6.73] [  500.0,  8.01] [  600.0,  8.81] [  800.0,  9.87] [ 1000.0, 10.43] [ 1500.0, 11.17]
BensonThermodynamicBase(c-(h)/3-(c)):	Reference: 'Benson20210129'
H298: -10.01 S298:  30.29 [  300.0,  7.74] [  400.0,  9.24] [  500.0, 10.62] [  600.0, 12.84] [  800.0, 14.59] [ 1000.0, 14.77] [ 1500.0, 17.58]
BensonThermodynamicBase(c-(h)/2-(c)/2):	Reference: 'Benson20210129'
H298:  -5.00 S298:   9.65 [  300.0,  5.59] [  400.0,  7.08] [  500.0,  8.43] [  600.0,  9.53] [  800.0, 11.23] [ 1000.0, 12.48] [ 1500.0, 14.25]
BensonThermodynamicBase(c-(h)-(c)/3):	Reference: 'Benson20210129'
H298:  -2.14 S298: -11.43 [  300.0,  4.90] [  400.0,  6.73] [  500.0,  8.01] [  600.0,  8.81] [  800.0,  9.87] [ 1000.0, 10.43] [ 1500.0, 11.17]
BensonThermodynamicBase(c-(h)/3-(c)):	Reference: 'Benson20210129'
H298: -10.01 S298:  30.29 [  300.0,  7.74] [  400.0,  9.24] [  500.0, 10.62] [  600.0, 12.84] [  800.0, 14.59] [ 1000.0, 14.77] [ 1500.0, 17.58]
BensonThermodynamicBase(c-(h)/2-(c)/2):	Reference: 'Benson20210129'
H298:  -5.00 S298:   9.65 [  300.0,  5.59] [  400.0,  7.08] [  500.0,  8.43] [  600.0,  9.53] [  800.0, 11.23] [ 1000.0, 12.48] [ 1500.0, 14.25]
BensonThermodynamicBase(c-(h)-(c)/3):	Reference: 'Benson20210129'
H298:  -2.14 S298: -11.43 [  300.0,  4.90] [  400.0,  6.73] [  500.0,  8.01] [  600.0,  8.81] [  800.0,  9.87] [ 1000.0, 10.43] [ 1500.0, 11.17]
BensonThermodynamicBase(c-(h)/3-(c)):	Reference: 'Benson20210129'
H298: -10.01 S298:  30.29 [  300.0,  7.74] [  400.0,  9.24] [  500.0, 10.62] [  600.0, 12.84] [  800.0, 14.59] [ 1000.0, 14.77] [ 1500.0, 17.58]
BensonThermodynamicBase:	Reference: 'InternalSymmetry-B(B1)(B2)(B2)(B2) (27)'
H298:   0.00 S298:  -6.55
BensonThermodynamicBase:	Reference: 'Optical Symmetry Correction (6.0)'
H298:   0.00 S298:   3.56
BensonThermodynamicBase(cyclohexane ring):	Reference: 'StandardCycles'
H298:  -0.36 S298:  18.80 [  300.0, -5.80] [  400.0, -4.10] [  500.0, -2.90] [  600.0, -1.30] [  800.0,  1.10] [ 1000.0,  2.20] [ 1500.0,  3.30]

-------------- Total --------------
BensonThermodynamicBase(Total):	Reference: 'Sum Total'
H298: -51.81 S298: 101.34 [  300.0, 48.89] [  400.0, 65.05] [  500.0, 78.28] [  600.0, 92.24] [  800.0,108.17] [ 1000.0,115.24] [ 1500.0,132.30]
-------------- NASA Polynomial --------------
mol                     c   9h  18          G    300.00   2000.00   1000.00    1
+7.61087250e+01-9.54869876e-02+1.28741136e-04-6.11350309e-08+9.72273379e-12    2
-6.67907640e+04-3.75122954e+02+1.03990569e+01-3.14689421e-03+2.56085770e-04    3
-3.29863812e-07+1.24511979e-10-4.54750077e+04-1.63501085e+01                   4


```
